### ISSUE TITLE
文章教程中部署合约部分失败

### ISSUE THREAD

**Issue by calmzealA** [idoall/truffle_solidity_contractsExample#1]
mshk_Contract = web3.eth.contract(abi);

错误如下：
”ReferenceError: 'abi' is not defined
at <anonymous>:1:35”

改成 
mshk_Contract = web3.eth.contract(mshk_abi);
可以继续。

但是到了
mshk_hello = mshk_Contract.new 。。之后
并没有预期的
> Contract mined! Address: 0x1d055281899007cbe6865a48d0a79239dac8e486
[object Object]

而是

> {
  abi: [{
      constant: true,
      inputs: [{...}],
      name: "print",
      outputs: [{...}],
      payable: false,
      stateMutability: "pure",
      type: "function"
  }, {
      constant: true,
      inputs: [],
      name: "say",
      outputs: [{...}],
      payable: false,
      stateMutability: "pure",
      type: "function"
  }],
  address: undefined,
  transactionHash: null
}

再之后 

> > mshk_hello.say()
TypeError: 'say' is not a function
    at <anonymous>:1:1

请问是什么情况？ 谢谢

**Comment by idoall** [comment]
感谢您指出文章中的一处错误，已经更新。

部署合约没有预期的效果，是不成功的。所以不能调用合约的say()方法。

部署合约是要挖矿的，您是否在没有挖矿的情况下部署合约？

**Comment by calmzealA** [comment]
@idoall 谢谢您的及时回复。我是部署之后，再挖矿的可以吗？刚开始学习，不太明白

**Comment by idoall** [comment]
应该是可以的。

以太坊在部署合约的时候，需要消耗`gas`，同时需要区块确认，如果不挖矿是无法部署合约的。

如果不行可以重新按这篇文章的步骤操作一次，不要遗漏任何步骤。
[https://mshk.top/2017/11/truffle-4-0-geth-1-7-2-testrpc/](https://mshk.top/2017/11/truffle-4-0-geth-1-7-2-testrpc/)

**Comment by calmzealA** [comment]
另外，在
mshk_hello = mshk_Contract.new({from:acc0, data:mshk_bytecode, gas:300000}, function(e, contract){。。。

这里，报了个acc0未定义
我按照其他文章加了这个变量，不知道是否正确
acc0 = web3.eth.accounts[0]


----
acc0的声明，在文章中有描述，见：[https://mshk.top/2017/11/truffle-4-0-geth-1-7-2-testrpc/#623_Geth](https://mshk.top/2017/11/truffle-4-0-geth-1-7-2-testrpc/#623_Geth)

**Comment by calmzealA** [comment]
ok，我再试试，之前初始化创世区块跟文章里有点不一样

**Comment by calmzealA** [comment]
@idoall 确实可以。我这里之前是truffle4.0.1，另外初始化创世区块不一样，而且没按照rpc方式启动。

ps: 在windows 下，truffle init 之后，使用 truffle命名 都需要加上.cmd
比如 
truffle.cmd compile

因为windows默认会使用当前目录下的truffle.js来执行了。

**Comment by idoall** [comment]
解决就好，如果再有问题，可以提到[https://mshk.top](https://mshk.top)，这里有时被GFW，看不到
